lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem' # Chemin vers la clé publique
    pass_phrase: '' # Passphrase utilisée lors de la génération des clés (laisser vide si non utilisée)
    token_ttl: 3600 # Durée de vie du token (en secondes, ici 1 heure)
